mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"),
    path('profile/', user_views.profile, name="profile"),
] + static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from .views import ProductDetail, CategoryDetail, Home, SubCategoryDetail


urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("discount/", views.discountPage, name="discount"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    #path("tracker/", views.home, name="trackingStatus"),
    #path("search/", views.home, name="search"),
    path("product_detail/<int:pk>", ProductDetail.as_view(), name="product_detail"),
    path("category_detail/<int:pk>", CategoryDetail.as_view(), name="category_detail"),
    path("subcategory_detail/<int:pk>", SubCategoryDetail.as_view(), name="subcategory_detail"),
    path("checkout", views.checkout, name="checkout"),
    path("new_product/", views.new_product_Page, name="new_product"),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

ON_DISCOUNT = [
  ('Y', 'yes'),
  ('N', 'no')
]

LABEL_CHOICES = [
  ('P', 'primary'),
  ('S', 'secondary'),
  ('D', 'danger')
]


class Category(models.Model):
  name = models.CharField(max_length=200)

  def __str__(self):
    return self.name

class SubCategory(models.Model):
  name = models.CharField(max_length=200)

  def __str__(self):
    return self.name

class Product(models.Model):
  product_id = models.AutoField
  product_name = models.CharField(max_length = 50)
  label = models.CharField(choices=LABEL_CHOICES, max_length=1)
  on_discount = models.CharField(choices=ON_DISCOUNT, max_length=1)
  category = models.ForeignKey(Category, related_name='Category', blank=True, on_delete=models.CASCADE)
  sub_category = models.ForeignKey(SubCategory, related_name='SubCategory', blank=True, on_delete=models.CASCADE)
  discount_price = models.FloatField()
  price = models.FloatField(default=0)
  desc = models.CharField(max_length = 300, default="")
  pub_date = models.DateTimeField(auto_now_add=False)
  image = models.ImageField(upload_to="store/images", default="")

  def get_absolute_url(self):
    return reverse('product_detail', args=(self.id,))

  def __str__(self):
    return self.product_name

class Contact(models.Model):
  msg_id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=50)
  email = models.CharField(max_length=50, default="")
  phone = models.CharField(max_length=70, default="")
  desc = models.CharField(max_length=500, default="")

  def __str__(self):
    return self.name


class OrderLine(models.Model):
  item = models.ForeignKey(Product, on_delete=models.CASCADE)

  def __str__(self):
    return self.name


class Order(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  item = models.ManyToManyField(OrderLine)
  start_date = models.DateTimeField(auto_now_add=True)
  ordered_date = models.DateTimeField()
  ordered = models.BooleanField(default=False)
  pass

  def __str__(self):
    return self.username

store/views.py
from django.shortcuts import render
from .models import Product, Contact, Category, SubCategory
from math import ceil
from django.views.generic import DetailView, ListView
from datetime import datetime, date, time, timedelta


def about(request):
    return render(request, 'store/about.html')

class Home(ListView):
    model = Category
    template_name = 'store/home.html'
    context_object_name = 'home_list'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.distinct()
        context['products'] = Product.objects.all()
        context['sub_categories'] = SubCategory.objects.distinct()
        return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'store/product_detail.html'
    context_object_name = 'product'


class CategoryDetail(DetailView):
    model = Category
    template_name = 'store/category_detail.html'
    context_object_name = 'category'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.distinct()
        context['sub_categories'] = SubCategory.objects.distinct()
        category = context['category']
        products = Product.objects.filter(category=category)
        context['products'] = products
        return context

class SubCategoryDetail(DetailView):
    model = SubCategory
    template_name = 'store/subcategory_detail.html'
    context_object_name = 'sub_category'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.distinct()
        context['sub_categories'] = SubCategory.objects.distinct()
        sub_category = context['sub_category']
        products = Product.objects.filter(sub_category=sub_category)
        context['products'] = products
        return context

def new_product_Page(request):
    date = datetime.today()
    start_week = date - timedelta(date.weekday())
    end_week = start_week + timedelta(7)
    context = {
        'products': Product.objects.filter(pub_date__range=[start_week, end_week]).order_by('-pub_date'),
        'categories': Category.objects.distinct(),
        'sub_categories': SubCategory.objects.distinct()
    }
    return render(request, 'store/new_product.html', context)

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        print(name, email, phone, desc)
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
    return render(request, 'store/contact.html')

def discountPage(request):
    context = {
        'products': Product.objects.all(),
        'categories':Category.objects.distinct(),
        'sub_categories': SubCategory.objects.distinct()
    }
    return render(request, 'store/discount.html', context)

def tracker(request):
    return render(request, 'store/tracker.html' )

def search(request):
    return render(request, 'store/search.html' )

def checkout(request):
    return render(request, 'store/checkout.html')

#not in use
def discountPageNotInUse(request):
    allProds = []
    catprods = Product.objects.values('category', 'id')
    cats = {item['category'] for item in catprods}
    for cat in cats:
        prod = Product.objects.filter(category = cat)
        n = len(prod)
        nSlides = n//4 + ceil((n/4)-(n//4))
        allProds.append([prod,range(1, nSlides), nSlides])
    params = {'allProds': allProds}
    return render(request, 'store/discount.html', params)

store/templates/store/about.html
<title>about</title>
 <style type="text/css">
    #margintop{
    margin-top: 70px;
    }
  </style>
{% extends "store/base.html" %}
{% block content %}
<div id="margintop" class ="p-5">
    <main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Orion Cart</h1>
      <p>Orion Cart is a Private Limited, d/b/a Orion is an Estonian e-commerce company based in Tallinn, Estonia. It was founded by Modith Hadya in 2020. The company initially focused on book sales, before expanding into other product categories such as consumer electronics, fashion, home essentials & groceries, and lifestyle products. </p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Reference</h2>
        <p> Software development Academy </br>Tallinn, Estonia

Akademia SDA OÜ</br> Maakri 19/1, PO box 43, </br>10145 Tallinn</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Modith Hadya</h2>
        <p>Estonia, Tallinn</br>
Email: modith.hadya@gmail.com</br>

LinkedIn: https://www.linkedin.com/in/modith-hadya-leelananda-09425346/</br>
Github: https://github.com/PHNX-MOD/Projects/blob/master/projects.md </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

</main>
</div>
{% endblock content %}

store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  {% block title %}
    {% if title %}
      <title>{{ title }}</title>
    {% else %}
      <title>Orion store</title>
    {% endif %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- Material Design Bootstrap -->
  <link href= "{% static 'store/css/mdb.min.css' %}"  rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'store/css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'home' %}" >
        <strong class="blue-text">Orion Cart</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'home' %}">Home <i class="fas fa-home"></i>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'about' %}">About Us<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href=#
              >Tracker</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href=# >Sell
              </a>
          </li>
        </ul>

        <!-- Right -->
        {% if user.is_authenticated %}

        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> <span id="cart">0</span> </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block">Cart</span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'profile' %}" class="nav-link border border-light rounded waves-effect"
              >
              <i class="fas fa-user-circle"></i>Account:{{user.get_username}}
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'logout' %}" class="nav-link waves-effect" >
              <i class="fas fa-sign-out-alt"></i>Sign out
            </a>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item" data-container="body" id="popcart" data-toggle="popover" data-placement="bottom" data-html="true" data-content="Vivamus
sagittis lacus vel augue laoreet rutrum faucibus.">
            <a class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> <span id="cart">0</span> </span>
              <i class="fas fa-shopping-cart"></i>
              <span >Cart</span>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'login' %}" class="nav-link waves-effect" >
              <i class="fas fa-sign-in-alt"></i> Sign in
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'register' %}" class="nav-link border border-light rounded waves-effect"
              >
              <i class="fas fa-user-circle"></i>Register
            </a>
          </li>
        </ul>
        {% endif %}

      </div>

    </div>
  </nav>
  <!-- Navbar -->

  <div class="container">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  </div>


  {% block content %}{% endblock %}

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="{% url 'home' %}"
        role="button">Download catalogue
        <i class="fas fa-download ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href=# >
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href=# >
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href=# >
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href=# >
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href=# >
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href=# >
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href=# >
        <i class="fab fa-github mr-3"></i>
      </a>

    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      <a href="{% url 'contact' %}" > contact us </a>
    </div>
    <!--/.Copyright-->


  </footer>
  <!--/.Footer-->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  <!-- SCRIPTS -->
  <!-- JQuery -->
 <!-- <script type="text/javascript" src= "{% static 'store/js/jquery-3.4.1.min.js' %}"></script>-->
  <!-- Bootstrap tooltips -->
  <!-- <script type="text/javascript" src="{% static 'store/js/popper.min.js' %}" ></script>-->
  <!-- Bootstrap core JavaScript -->
  <!-- <script type="text/javascript" src="{% static 'store/js/bootstrap.min.js' %}"></script> -->
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'store/js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
  {% block js %} {% endblock %}
</body>

</html>

store/templates/store/checkout.html
this is checkout page

store/templates/store/contact.html
 <style type="text/css">
    #margintop{
    margin-top: 70px;
    margin-left:400px;
    margin-right:400px;
    }
  </style>
{% extends "store/base.html" %}
{% load static %}
{% block content %}
<div id="margintop" class ="p-5">
    <h3><strong>Contact us</strong></h3>
<form action="/contact/" method="post">{% csrf_token %}
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" name="name" placeholder="Enter your name">
  </div>
  <div class="form-group">
    <label for="name">Email</label>
    <input type="email" class="form-control" name="email" placeholder="Enter your Email">
  </div>
  <div class="form-group">
    <label for="name">Phone number</label>
    <input type="tel" class="form-control" name="phone" placeholder="Enter your phone number">
  </div>
  <div class="form-group">
    <label for="desc">Description</label>
    <textarea class="form-control" name="desc" rows="3"></textarea>
  </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
</div>
{% endblock content %}

store/templates/store/discount.html
<style>
  .navbar .nav-item .dropdown-menu .dropdown-item{
    color:black  ! important;
  }
  .navbar .nav-item .dropdown-menu .dropdown-item:hover{
      color: white  ! important;
      background-color:black;
      opacity:0.8;
  }
  .col-md-6 img {
    width:227px;
    height: 242px;
   }
</style>

{% extends "store/base.html" %}
{% block content %}
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Best offers on Fashion</strong>
              </h1>

              <p>
                <strong>Buy today and get the best discount available</strong>
              </p>

              <a href="{% url 'discount' %}" class="btn btn-outline-white btn-lg">UPTO 60% Discount
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Great deals on Electronics</strong>
              </h1>

              <p>
                <strong>Buy today and get the best discount available</strong>
              </p>


              <a href="{% url 'discount' %}" class="btn btn-outline-white btn-lg">upto 40% discount
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Best Deals on cosmetics</strong>
              </h1>
              <p>
                <strong>Buy today and get the best discount available</strong>
              </p>

              <a href="{% url 'discount' %}" class="btn btn-outline-white btn-lg">Upto 20% Discount
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
          <a href="{% url 'home' %}"><span class="navbar-brand" >All Products:</span></a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">

            <li class="nav-item dropdown ">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for i in request.session.categories %}
                <a class="dropdown-item" href=#> {{i.category}} </a>
                <div class="dropdown-divider"></div>
                {% endfor %}
              </div>
            </li>
            <li class="nav-item dropdown ">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sub-Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown ">
                {% for i in request.session.sub_categories %}
                <a class="dropdown-item" href=#> {{i.sub_category}} </a>
                <div class="dropdown-divider"></div>
                {% endfor %}
              </div>
            </li>
            <li>
               <a class="nav-link active" href="{% url 'discount' %}" role="button"  aria-haspopup="true" aria-expanded="false">
                Discount
              </a>
            </li>
            <li>
               <a class="nav-link active" href="{% url 'new_product' %}" role="button"  aria-haspopup="true" aria-expanded="false">
                New Products
              </a>
            </li>
          </ul>
          <!-- Links -->
          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for i in products %}
            {% if i.get_on_discount_display == 'yes' %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">


            <!--Card-->
            <div class="card">
              <!--Card image-->
              <div class="view overlay">
                <img src='/media/{{i.image}}' class="card-img-top"
                  alt="">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ i.category }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{% url 'product_detail' i.pk %}" class="dark-grey-text">{{ i.product_name }}
                      </a>
                  </strong>
                </h5>

                <h6 class="font-weight red-text">
                  <del>{{ i.price }}€</del>
                </h6>
                <h6 class="font-weight-bold blue-text">
                    {{ i.discount_price }}€
                </h6>
                <button id="pr{{i.id}}" class="btn btn-info btn-sm cart" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
            {% endif %}
        {% endfor %}
        </div>
        <!--Grid row-->


      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>

          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>

{% endblock content %}


{% block js %}

<script>
if(localStorage.getItem('cart') == null){
var cart = {};
}
else
{
cart = JSON.parse(localStorage.getItem('cart'));
}
$('.cart').click(function(){
console.log('clicked');
var idstr = this.id.toString();
console.log(idstr);
if (cart[idstr] !=undefined){
cart[idstr] = cart[idstr] + 1;
}
else
{
cart[idstr] = 1;
}
console.log(cart);
localStorage.setItem('cart', JSON.stringify(cart));
document.getElementById('cart').innerHTML = Object.keys(cart).length;
});
$('#popcart').popover();
document.getElementById("popcart").setAttribute('data-content','<h6>Cart</h6>');
</script>

{% endblock %}

store/templates/store/product_list.html
{% extends "store/base.html" %}
{% block content %}
{% for product in products %}
<h5>{{ product }}</h5>
{% endfor %}
{% endblock content %}

store/templates/store/products.html
{% extends "store/base.html" %}
{% load static %}
{% block content %}
<h1>product list page</h1>
{% endblock content %}

store/templates/store/tracker.html
{% extends "store/base.html" %}
{% load static %}
{% block content %}
<h1>this is the tracker page</h1>

{% endblock content %}